import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // DAQ sidebar - manually specify each category to restore structure while excluding software
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Ethernet-DAQ 使用說明書',
      link: { type: 'generated-index', slug: 'ethan', title: 'Ethernet-DAQ 使用說明書', description: '工業級乙太網路採集卡，支援長距離穩定傳輸。' },
      items: [{ type: 'autogenerated', dirName: 'daq/ethan' }],
    },
    {
      type: 'category',
      label: 'USB-DAQ 使用說明書',
      link: { type: 'generated-index', slug: 'usb-daq', title: 'USB-DAQ 使用說明書', description: '這裡是 WPC 所有 USB 數據採集卡的技術文件中心。' },
      items: [{ type: 'autogenerated', dirName: 'daq/usbdaq' }],
    },
    {
      type: 'category',
      label: 'WIFI-DAQ 使用說明書',
      link: { type: 'generated-index', slug: 'wifi-daq', title: 'WIFI-DAQ 使用說明書', description: '這裡是 WPC 所有無線數據採集卡的技術文件中心。' },
      items: [{ type: 'autogenerated', dirName: 'daq/wifidaq' }],
    },
    {
      type: 'category',
      label: '馬達驅動 (Motion)',
      link: { type: 'generated-index', title: '運動控制解決方案', description: '包含 EDriveST 與 EDriveSRV 系列馬達驅動器手冊。' },
      items: [{ type: 'autogenerated', dirName: 'Motion' }],
    },
    {
      type: 'category',
      label: '無人機 (Drone)',
      link: { type: 'generated-index', title: '無人機系統文檔' },
      items: [{ type: 'autogenerated', dirName: 'Drone' }],
    },
  ],

  // Software sidebar - separate top-level category
  softwareSidebar: [{ type: 'autogenerated', dirName: 'software' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
