import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // DAQ sidebar
  tutorialSidebar: [
    'daq-intro',
    {
      type: 'category',
      label: 'Ethernet-DAQ 使用說明書',
      link: { type: 'generated-index', slug: 'ethan' },
      items: [{ type: 'autogenerated', dirName: 'daq/ethan' }],
    },
    {
      type: 'category',
      label: 'USB-DAQ 使用說明書',
      link: { type: 'generated-index', slug: 'usb-daq' },
      items: [{ type: 'autogenerated', dirName: 'daq/usbdaq' }],
    },
    {
      type: 'category',
      label: 'WIFI-DAQ 使用說明書',
      link: { type: 'generated-index', slug: 'wifi-daq' },
      items: [{ type: 'autogenerated', dirName: 'daq/wifidaq' }],
    },
    {
      type: 'category',
      label: 'STEM 使用說明書',
      link: { type: 'generated-index', slug: 'stem' },
      items: [{ type: 'autogenerated', dirName: 'daq/stem' }],
    },
  ],

  // Software sidebar - separate top-level category
  softwareSidebar: [{ type: 'autogenerated', dirName: 'software' }],

  // Embedded Systems sidebar
  embeddedSidebar: [
    'embedded_intro',
    { type: 'autogenerated', dirName: 'embedded_systems' },
  ],

  // Drone sidebar
  droneSidebar: [
    'drone_intro',
    { type: 'autogenerated', dirName: 'Drone' },
  ],

  // Driver sidebar
  driverSidebar: [{ type: 'autogenerated', dirName: 'driver' }],

};

export default sidebars;
